#!/bin/bash

unset MAISTRA_BRANCH
unset BOOKINFO_PROJECT
unset BOOKINFO_APP_URL
unset BOOKINFO_DEST_RULES_ALL_URL
unset BOOKINFO_VIRTUAL_SERVICE_V1_URL
unset BOOKINFO_GATEWAY_URL
unset CONTROL_PROJECT

